spring.application.name=demo
server.port=8081
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/siteFoot
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
apisports.key=e3ee25c24cdfc060264e59c8f76c43bd
apisports.baseUrl=https://v3.football.api-sports.io



